name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15
      
      - name: ESLint setup
        run: npm init @eslint/config
      
      - name: ESLint (JS/TS) Action
        uses: iCrawl/action-eslint@v1
